#!/usr/bin/env bash
# scaffold_cmakelists.sh — Generate a ROS2 CMakeLists.txt skeleton from a ROS1 one.
# Usage: bash scaffold_cmakelists.sh <ros1_CMakeLists.txt>
#
# Reads the ROS1 file to extract project name, executables, and find_package
# components, then prints a ROS2-style CMakeLists.txt to stdout.

set -euo pipefail
SRC="${1:?usage: scaffold_cmakelists.sh <ros1_CMakeLists.txt>}"
[[ -f "$SRC" ]] || { echo "not a file: $SRC" >&2; exit 2; }

PROJ=$(grep -oE 'project\([A-Za-z0-9_]+\)' "$SRC" | head -n1 | sed -E 's/project\(([^)]+)\)/\1/')
[[ -z "$PROJ" ]] && PROJ="my_pkg"

mapfile -t COMPS < <(grep -A 20 'find_package(catkin' "$SRC" \
                       | tr -d '()' | tr ',' ' ' \
                       | tr ' ' '\n' \
                       | sed -E 's/REQUIRED|COMPONENTS|find_package|catkin//g' \
                       | grep -E '^[a-z][a-z0-9_]+$' || true)

mapfile -t EXES < <(grep -oE 'add_executable\([A-Za-z0-9_]+' "$SRC" \
                      | sed -E 's/add_executable\(//')

# Map ROS1 components to ROS2 equivalents
declare -A MAP=(
  [roscpp]="rclcpp"
  [rospy]=""                   # python build, handled differently
  [tf]="tf2 tf2_ros tf2_geometry_msgs"
  [actionlib]="rclcpp_action"
  [actionlib_msgs]="action_msgs"
  [nodelet]="rclcpp_components"
  [pcl_ros]="pcl_conversions"
)
declare -A ROS2_DEPS=()
for c in "${COMPS[@]}"; do
  m="${MAP[$c]:-}"
  if [[ -n "$m" ]]; then
    for d in $m; do ROS2_DEPS[$d]=1; done
  else
    ROS2_DEPS[$c]=1
  fi
done

# Always include core
ROS2_DEPS[ament_cmake]=1
ROS2_DEPS[rclcpp]=1

cat <<EOF
# ============================================================
# Generated by scaffold_cmakelists.sh from $SRC
# Review and edit before committing.
# ============================================================
cmake_minimum_required(VERSION 3.8)
project($PROJ)

if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 17)
endif()
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

EOF

for d in "${!ROS2_DEPS[@]}"; do
  echo "find_package($d REQUIRED)"
done

cat <<'EOF'

# include_directories(include)

# add_library(${PROJECT_NAME}_lib SHARED src/foo.cpp)
# ament_target_dependencies(${PROJECT_NAME}_lib rclcpp ...)

EOF

for exe in "${EXES[@]}"; do
  echo "add_executable($exe src/$exe.cpp)"
  printf "ament_target_dependencies($exe"
  for d in "${!ROS2_DEPS[@]}"; do
    [[ "$d" == "ament_cmake" ]] && continue
    printf " $d"
  done
  echo ")"
  echo
done

cat <<EOF

install(TARGETS
EOF
for exe in "${EXES[@]}"; do echo "  $exe"; done
cat <<'EOF'
  DESTINATION lib/${PROJECT_NAME})

install(DIRECTORY launch config rviz
  DESTINATION share/${PROJECT_NAME}
  OPTIONAL)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
EOF
